### ISSUE TITLE
Hi guys,

### ISSUE THREAD

**Issue by hmendezm** [jameskleeh/angular-confirm#11]
I am trying to use angular-confirm with requirjs but when I clikc the button nothing happens. IF I use it without Requirejs it work

**Comment by jameskleeh** [comment]
You'll have to read the documentation in requirejs about including non AMD in your project: http://requirejs.org/docs/api.html#config-shim

**Comment by hmendezm** [comment]
Thanks James for the feedback. I already did the Shim config. I do not get
any error but the window is not show up. I am using other directives such
as ui-sortable without any problem so ... Thx I will figure out or find
other directive that fit my needs.

Thx for the work in this directive!!

Best

**Comment by abhayastudios** [comment]
Make sure to include 'angular-confirm' as a dependency of your module.
