### ISSUE TITLE
CSS problems

### ISSUE THREAD

**Issue by sterichards** [jameskleeh/angular-confirm#19]
I get this when including and using angular-confirm - http://imgur.com/IDyUO0O

I'm sure this is because of some existing CSS but i'm not good enough at CSS to debug it. Are there any easy methods you're aware of that I can use to get this working without tiring CSS debugging?

**Comment by jameskleeh** [comment]
This looks like you aren't including the ui-bootstrap that contains the templates. Should be something like "ui-bootstrap-tpls"
