### ISSUE TITLE
things in template  pass to the $confirm?

### ISSUE THREAD

**Issue by feaswcy** [jameskleeh/angular-confirm#22]
I am  in trouble with use templateUrl which includes  angular validation(the original),and i want to pass <code>Form.$valid</code> to the confirm dialogo function  <code>ok</code>  but  it didn't work in the controller with <code>then(function(isValid){console.log(isValid)})</code>....or is there any way to link submit action to this ok function ...
much appreciations if you can deal with it cause i am a new one in angular js....

**Comment by jameskleeh** [comment]
So essentially the OK button should only work if the form is valid?

If so, you can probably get away with having that logic in your view. Another option is to provide a controller (use the existing one as a starting point) and do your logic there.
