### ISSUE TITLE
$modal is now deprecated. Use $uibModal instead.

### ISSUE THREAD

**Issue by dimitriscsd** [jameskleeh/angular-confirm#24]
Hello.

Angular UI (version: 0.14.3) have changed the naming convention of their services. They prefix them with 'uib' now.

Could you please make this change on your library as well so we stop getting the deprecation warning whenever we use it?

Thanks in advance.

**Comment by jameskleeh** [comment]
I'll have to start a new branch for this as it is a breaking change

**Comment by dimitriscsd** [comment]
So is this planned to happen? From my research it looks like it's a simple rename in this case. Separate branch sounds good, I suppose. However maybe the old functionality should be on another branch and the up-to-date stuff on master? Just a suggestion :)

**Comment by alexweber** [comment]
:+1:

**Comment by jameskleeh** [comment]
1.2.0 is released. Thank you for the suggestion!

**Comment by sargue** [comment]
You forgot to rebuild the minified file, drove me mad to find it...;-)

**Comment by dimitriscsd** [comment]
I can confirm that the minified version of the file is still using the old stuff.

Thanks for the heads up sargue.

**Comment by jameskleeh** [comment]
Ugh I apologize. It seems like I can never get this right 100%.
