### ISSUE TITLE
HTML Support in message

### ISSUE THREAD

**Issue by raghu-romp** [jameskleeh/angular-confirm#31]
Hey,

I was trying to make the message look like "Are you sure to delete **Bob**?". However the message there doesn't seem to be a HTML support in angular-confirm. 

I love this little Angular plugin and would appreciate if there is a way to put in some HTML into the message.

Thanks,
Raghu

**Comment by antidote2** [comment]
I think custom template with ng-bind-html should work

**Comment by jameskleeh** [comment]
I agree with @anatolibarski. The use of a custom template is what you need here
