### ISSUE TITLE
Option to pass Data without copying it

### ISSUE THREAD

**Issue by lethargicgeek** [jameskleeh/angular-confirm#33]
Would like an option to pass data to Angular-Confirm without copying it.  This would allow the ability to have inputs on the confirmation modal that can update the calling parent scope.

**Comment by jameskleeh** [comment]
I'm a little confused on what you mean here. Can you submit a PR so we can have an implementation to discuss?

**Comment by lethargicgeek** [comment]
Sure thing, will submit a pull request by tomm night.  Thanks!

**Comment by lethargicgeek** [comment]
I"m a terrible person and got caught up in life :/  Closing the issue since I'm too terrible to follow up on it.
