### ISSUE TITLE
Hardcoded interpolation symbols '{{' '}}'

### ISSUE THREAD

**Issue by frozonfreak** [jameskleeh/angular-confirm#35]
My project uses '[[' instead of '{{' as interpolation symbol
Is it possible to change the symbols via configurations

**Comment by jameskleeh** [comment]
I don't think that is a common enough use case to warrant a parameter. You can simply use a custom template and it will meet your needs. You can define it in the `$confirmModalDefaults`.

**Comment by JohnnyEvo** [comment]
For the twig's user, it's common because "{{ }}" is the symbol for Twig too.

But your solution is ok, thank you :+1: 

http://twig.sensiolabs.org/
