### ISSUE TITLE
Unable to deploy to WebJars

### ISSUE THREAD

**Issue by ulejon** [jameskleeh/angular-confirm#36]
Hi,

I'm trying to deploy version 1.2.1 to http://www.webjars.org/bower.
I'm getting the following error:

Failed! No valid licenses found. Detected licenses: Apache The acceptable licenses on BinTray are at: https://bintray.com/docs/api/#_footnote_1 License detection first uses the package metadata (e.g. package.json or bower.json) and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the master branch of the GitHub repo. Since these methods failed to detect a valid license you will need to work with the upstream project to add discoverable license metadata to a release or to the GitHub repo.  If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Created Bower WebJar Fetched Bower zip Generated POM Converted dependencies to Maven Got Bower info Determined Artifact Name: github-com-Schlogen-angular-confirm Starting Deploy
Deploy!

**Comment by jameskleeh** [comment]
As you can see in the bower and package file a license is defined. You would have to tell me why the license defined there is not sufficient

**Comment by ulejon** [comment]
Seems to work for the latest version, 1.2.3, but not for 1.2.1.
