### ISSUE TITLE
Error: [$injector:unpr] Unknown provider: $modalProvider <- $modal <- $confirm

### ISSUE THREAD

**Issue by realdammy** [jameskleeh/angular-confirm#37]
Hello,
Thanks for this wonderful plugin. I am having issues using the plugin. Anytime i included the 'angular-confrim' module in my App.module, i get the error below

Error: [$injector:unpr] Unknown provider: $modalProvider <- $modal <- $confirm
Here's my App module config
var App= angular.module('escrow',['datatables','datatables.bootstrap','ngRoute','datatables.buttons','angular-confirm','ui.bootstrap'])

And here is my controller
App.controller('BankMerchantListCtrl',function($scope, $compile, $confirm, $uibModal, DTOptionsBuilder, DTColumnBuilder,BankService) {

**Comment by jameskleeh** [comment]
What version of ui.bootstrap? What version of angular-confirm?

**Comment by realdammy** [comment]
Hello I just realized the version of the $cofirm project on demo site (http://schlogen.github.io/angular-confirm/) is different from the one on github. The one on the demo site uses an older version of bootstrap UI. But after pulling the $confim project from github, everything works fine. Thanks alot.
