### ISSUE TITLE
Add Support to Act Like JS Confirm()

### ISSUE THREAD

**Issue by snowyaaron1** [jameskleeh/angular-confirm#43]
This should have similar functionality to confirm() in JS

A Boolean, indicating whether "OK" or "Cancel" was clicked in the dialog box:
true - the user clicked "OK"
false - the user clicked "Cancel" (or the "x" (close) button in the top right corner that is available in all major browsers, except Firefox)

Example:

 if (document.getElementById("back-button").disabled ||
                    $confirm({title:'',text: "The 'Back' button will be disabled if a field " +
                    "name is changed. Press 'OK' to confirm.", ok: 'OK', cancel: 'Cancel'}) == true)

I have read your documentation and do not see an example like this.

**Comment by jameskleeh** [comment]
Unfortunately that would have to be a blocking operation in order for it to function like you describe. I'm certain that would be an undesirable change for the vast majority of users.
