### ISSUE TITLE
How to use with template

### ISSUE THREAD

**Issue by Jerome2606** [jameskleeh/angular-confirm#45]
Hello,

Do you have a fully sample with a custom template file ?

I don't understand where to insert the $uibModal service.

**Comment by jameskleeh** [comment]
@Jerome2606 Checkout the demo page here http://schlogen.github.io/angular-confirm/

**Comment by Jerome2606** [comment]
@Schlogen I check this page but I don't well understand how it works. I have this modal:

`<div class="modal fade" id="supprimer" role="dialog">
    <div class="modal-dialog modal-suppression">
        <div class="modal-content">
            <div class="modal-body">
                <h3>Êtes-vous sûr de vouloir supprimer ce TAF?</h3>
                <div class="field-group">
                    <a href="#" ng-click="ok()">OUI</a>
                    <a href="#" ng-click="cancel()">NON</a>
                </div>
            </div>
        </div>
    </div>
</div>`

But I don't understand where to inject $uibModal service.

Here's the directive where I want to use it:

`scope.tafDeleteToParent = function (taf) {
                        $confirm({}, { templateUrl: '/App/Main/tafs/tsConfirmDeleteTaf.cshtml' })
                            .then(function() {
                                tafDelete(taf);
                            });
                    }`

**Comment by jameskleeh** [comment]
So assuming that template exists at `path/to/your/template`:

```
$confirm({}, { templateUrl: 'path/to/your/template' })
  .then(function() {
    ...
  });
```

This exact example is under the "Settings" section of the demo page.

If you want to use it as a string:

```
$confirm({name: "Sally"}, { template: '<div class="modal fade" ...  </div>' })
  .then(function() {
    ...
  });
```

This exact example is under the "Settings" section of the demo page.

**Comment by Jerome2606** [comment]
Made it working with this code:

`<div id="supprimer">
    <div class="modal-content">
        <div class="modal-body">
            <h3>Êtes-vous sûr de vouloir supprimer ce TAF?</h3>
            <div class="field-group">
                <a href="#" ng-click="ok()">OUI</a>
                <a href="#" ng-click="cancel()">NON</a>
            </div>
        </div>
    </div>
</div>`

Thanks for you library :+1:

**Comment by buiminhhuy** [comment]
I want to use input to change data.name in template:
$confirm({name: "Sally"}, { template: '<div class="modal fade" ...  </div>' })
  .then(function() {
    ...
  });
How to get data.name in then funtion()?

**Comment by hkong** [comment]
I had the same question.  Take a look at this:  https://github.com/Schlogen/angular-confirm/issues/44.  I should have an example as soon as I get some time from my project.

**Comment by buiminhhuy** [comment]
Ok Thank You,
I have just got resolve this.
