### ISSUE TITLE
Unknown provider: $animateCssProvider <- $animateCss <- $uibModalStack <- $uibModal <- $confirm <- confirmDirective

### ISSUE THREAD

**Issue by PabloPG** [jameskleeh/angular-confirm#47]
Hello people,

when I test the plugin , I came across the following error:

`Unknown provider: $animateCssProvider <- $animateCss <- $uibModalStack <- $uibModal <- $confirm <- confirmDirective`

Angular-confirm version: 1.2.3
ui.bootstrap version: 1.2.4

`angular.module('app', ['ui.router', 'satellizer', 'angular-confirm', 'ui.bootstrap', 'ui.mask'])`

**Comment by jameskleeh** [comment]
Looks to me like the version of ui.bootstrap you are using is not compatible with the version of angular-animate.

**Comment by PabloPG** [comment]
Hm thanks, this version require angularjs 1.4.x, i was using 1.3.15
