### ISSUE TITLE
option to don't display the confirm modal

### ISSUE THREAD

**Issue by alainib** [jameskleeh/angular-confirm#58]
I look in the closed issues but don't found a help.

I made an interface with a list of button. on each button there is a confirm with yes/no.
http://awesomescreenshot.com/0465v52t3e

there is a lot of button so if the user needs to click 10 of them, the confirm message will be boring after 2/3 times. 
Is there a way to display inside the confirm modal a button to "ok i understand, stop showing confirm" so on other button click confirm will not show.

It is on same idea that how modern web browser handle popup . 

thanks

**Comment by jameskleeh** [comment]
@alainib There is a `confirmIf` option you can use. Set the option to a variable and assign it to false if you no longer want to prompt the user. You would have to do it via the `$confirm` service. You can use a custom template which has the button `ng-click=ok(true)` then:

`$confirm(...).then(function(wantToIgnore) {
  showConfirm = !wantToIgnore;
});`

**Comment by alainib** [comment]
very nice. Sorry i didn't find the "confirmIf" in the doc.

Another little question: 
is there a way to add a parametre in the directive for confirmIf  ? 
I have a list of items and for each multiple buttons doing differents task. i didn't want to remove the confirm for all the button but just for one task

`<button  ng-click="detele(id)" confirm="Delete ?" confirmIf="show.delete">delete </button>`
`<button  ng-click="edit(id)" confirm="Edit ?" confirmIf="show.edit">edit </button>`
`<button  ng-click="clone(id)" confirm="Clone ?" confirmIf="show.clone">clone </button>`

with `$scope.show = { "delete": true, "edit":true,"clone" : true } `
thanks for your time and very usefull module
