### ISSUE TITLE
Unable to inject

### ISSUE THREAD

**Issue by timendez** [jameskleeh/angular-confirm#60]
Using Angular 1, Typescript, Jade, installed via bower

Error: [$injector:strictdi] function($confirm, $timeout) is not using explicit annotation and cannot be invoked in strict mode
http://errors.angularjs.org/1.4.7/$injector/strictdi?p0=function(%24confirm%2C%20%24timeout)
    at processor.js:61
    at Function.annotate [as $$annotate](processor.js:61)
    at Object.invoke (processor.js:61)
    at processor.js:61
    at forEach (processor.js:61)
    at Object.<anonymous> (processor.js:61)
    at Object.invoke (processor.js:61)
    at Object.enforcedReturnValue [as $get](processor.js:61)
    at Object.invoke (processor.js:61)
    at processor.js:61

**Comment by simison** [comment]
@Schlogen actually these issues don't happen only regarding minification, but in Strict DI Mode: https://docs.angularjs.org/guide/production

**Comment by jameskleeh** [comment]
I recommend what Angular states:

It is recommended to automate the explicit annotation via a tool like ng-annotate when you deploy to production (and enable strict di mode)

Or use the minified version

**Comment by timendez** [comment]
How do I go about using the minified version?
