### ISSUE TITLE
WARNING: Tried to load angular more than once.

### ISSUE THREAD

**Issue by Bratkartoffl** [jameskleeh/angular-confirm#67]
Hello there,

when I include the `angular-confirm.min.js` file in my index.html and then inject it into my  `main.js` file, then I get the following warning shown in my console:

`WARNING: Tried to load angular more than once.`

Any Idea, why this warning is thrown?

Regards

**Comment by jameskleeh** [comment]
I don't think it has anything to do with this module. Angular itself is being included more than once on your page.

**Comment by Megale** [comment]
If you remove angular-confirm from your page do you still receive the warning?

**Comment by Bratkartoffl** [comment]
@Megale I tried that. I deleted the *js file include as well as the injection and then the warning was gone.. that why I thought it has something todo with this package.

**Comment by jameskleeh** [comment]
@Bratkartoffl It's something to do with your build. As you can see angular is not defined in this file: https://github.com/Schlogen/angular-confirm/blob/master/angular-confirm.min.js

**Comment by Bratkartoffl** [comment]
Okay i fixed it. It was a problem related to jquery. Thanks for your support!
