### ISSUE TITLE
How to specify size of modal

### ISSUE THREAD

**Issue by jomonkj** [jameskleeh/angular-confirm#7]
can't find directive attribute to specify size of modal (eg : confirm-size="samll")

**Comment by jameskleeh** [comment]
Currently you have 2 options.
1. Change it in the default settings `$confirmModalDefaults.`
2. Use the `$confirm` service instead of the directive.

I'll look into adding the settings into the directive

**Comment by jomonkj** [comment]
thanks

**Comment by jameskleeh** [comment]
This is done, see the demo for an example
