### ISSUE TITLE
Conflicting with the class of another modal

### ISSUE THREAD

**Issue by hardiksondagar** [jameskleeh/angular-confirm#72]
I'm using $confirm inside angular-ui's uibModalInstance and it's updating with the class of already opened modal. I'm using custom css class `modal-wide` in parent div of modal-dialog in first modal. 

Before $confirm modal
![](http://i.imgur.com/vxpXeuQ.png)

After $confirm modal open ( first modal's width back to medium as $confirm modal removed the modal-wide class )
![](http://i.imgur.com/x4bX7xU.png)

**Comment by jameskleeh** [comment]
That is ui-bootstrap doing that. My code doesn't do anything directly to the modal. The same thing would occur if you opened another modal with ui-bootstrap with the same options.
