### ISSUE TITLE
Return in promise data (when error)

### ISSUE THREAD

**Issue by kotmatpockuh** [jameskleeh/angular-confirm#73]
For example: i have an input in confirm. How can i get data.inputText in second function after .then()   (error processing)

**Comment by jameskleeh** [comment]
pass whatever variable you want to the `cancel` function. That variable will be passed to the error function

**Comment by kotmatpockuh** [comment]
@Schlogen but how to pass data on backdrop click?

**Comment by jameskleeh** [comment]
I don't believe ui-bootstrap modal supports that. if it does, link me the relevant docs
