### ISSUE TITLE
Page elements move a little after modal is shown

### ISSUE THREAD

**Issue by brunobastosg** [jameskleeh/angular-confirm#8]
Whenever a modal confirmation dialog is shown, the elements in the page move a little to the right. After it's closed, they move back left.

I thought it was an issue with my CSS, but I noticed it happens in angular-confirm's example page. Just click on the "Delete (Click 'Reset to clear')" button to see it.

http://schlogen.github.io/angular-confirm/

**Comment by ghost** [comment]
It appears the shift is from the removal of the vertical scroll bar which would account for ~15px of width.

**Comment by brunobastosg** [comment]
@twmulloy, yeah, I think that's the cause. I hadn't noticed the removal of the scroll bar before.

**Comment by jameskleeh** [comment]
@brunobastosg: @twmulloy is correct. It is being caused by the angular-ui modal. You would have to override the css of the modals to stop this from happening.
